# ==============================
# Spring Boot ??
# ==============================
spring.application.name=MSproject
spring.profiles.active=prod

# ==============================
# MySQL ?? DB ??
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/market_app?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1122
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / Hibernate ??
# ==============================
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ==============================
# ?? ??
# ==============================
server.servlet.session.timeout=30m
server.servlet.session.cookie.name=MSPROJECT_SESSION
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
# ?? ??? ?? false

# ==============================
# ?? ??
# ==============================
logging.level.org.springframework=ERROR
logging.level.com.MSproject=INFO
logging.level.org.hibernate.SQL=ERROR
